site_name: Python-Image-Fetcher
repo_name: 'Python-Image-Fetcher'
repo_url: 'https://github.com/BenAAndrew/Python-Image-Fetcher'
theme:
  name: null
  custom_dir: 'docs-template/mkdocs-material/material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo:
    icon: 'cloud'
  feature:
    tabs: false
